class LogNodeTransport
  public managesFiltering = true

  function new(mLog)
    m.nodeLogger = createObject("roSGNode", "LogNodeTransport")
    m.nodeLogger.mLog = mLog
  end function

  function log(args)
    items = m.nodeLogger._rawItems 
    if items.count() > m.nodeLogger.maxItems
      items.delete(0)
    end if
    item = { "level": args.level, "text": text, "name": args.name }
    items.push(item)

    m.nodeLogger._rawItems = items
  end function

end class