name: build
on:
  push:
    branches:
      - master
      - "release-*"
  pull_request:
    branches:
      - master
      - "release-*"
  workflow_dispatch:
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    env:
      #hardcode the coveralls token...it's not overly important to protect, and github actions won't allow forks to work with coveralls otherwise
      COVERALLS_REPO_TOKEN: "RuXDcEBMUavqJgSdr5svlXWGDjrDEWFUI"
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18.4.0"
      - run: npm ci
      - run: npm run build
      # - run: npm run publish-coverage
